### DISCUSSION TITLE
Linux Kernel package

### DISCUSSION THREAD

**Discussion by p5** [wolfi-dev/os#33208] [General]
I have been following the https://github.com/containers/bootc development, and had a crazy idea.  Theoretically we can build and boot a bare-metal system using only wolfi-os (and custom melange) packages.  This allows us to generate complete SBOMs of an entire OS, and have the same "zero CVEs" as we do in container images. 

I am in no way expecting Chainguard to pick this up as supported.  I thought it would be a cool project to showcase both tools.

Has anybody been able to work out the correct configuration to get a Linux Kernel package building?  I've been looking into it for the past hour-ish and have made progress, though said progress is slowing down when I reached the linux internals.

<details>

```
package:
  name: linux-kernel
  version: 5.15.170
  epoch: 1
  description: "Linux kernel packaged with Melange"
  copyright:
    - license: GPL-2.0-only
  dependencies:
    runtime:

environment:
  contents:
    packages:
      - busybox
      - autoconf
      - automake
      - build-base
      - wdiff
      - bison
      - flex
      - gcc
      - openssl-dev
      - bc
      - elfutils-dev
      - glibc
      - python3
    repositories:
      - https://packages.wolfi.dev/os
    keyring:
      - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub

pipeline:
  - uses: fetch
    with:
      uri: https://cdn.kernel.org/pub/linux/kernel/v5.x/linux-${{package.version}}.tar.xz
      expected-sha256: fd596545a3d6d93196db3fa29e4926e60900b9c05b3b9ccdee9e35d8e376e7a9
      strip-components: 0

  - runs: |
      cd linux-${{package.version}}
      make V=1 -j $(nproc)
```  

</details>
