### ISSUE TITLE
[Wolfi Package Request]: yamllint

### ISSUE THREAD

**Issue by kranurag7** [wolfi-dev/os#11649]
### What software would you like us to add to wolfi-os. Ideally include a URL to the project and its source.

https://github.com/adrienverge/yamllint 

### which versions of the software should we include?

latest

### Add some justification for why this specific package and versions are important.

This is a yaml linter and it'll be useful as a yaml linter. 

I tried the following but I was not able to get this to working stage. 
```yaml
package:
  name: yamllint
  version: 1.33.0
  epoch: 1
  description: "A linter for YAML"
  copyright:
    - license: GPL-3.0-only
  dependencies
  # runtime:
  #   - python3:

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - py3-pip
      - py3-setuptools
      - python3
      - wolfi-base

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/adrienverge/yamllint
      tag: v${{package.version}}
      expected-commit: 8713140e99914c0cb6e07364daedfb140847c3c5

  - runs: |
      python3 setup.py build

  - runs: |
      python3 setup.py install --prefix=/usr --root="${{targets.destdir}}"

  - uses: strip

update:
  enabled: true
  github:
    identifier: adrienverge/yamllint
    use-tag: true
```

### Please check all that apply

- [X] This package has an un-restrictive license
- [X] The package/versions proposed are actively maintained upstream
- [ ] I am interested in adding this package to Wolfi OS myself
- [ ] I am willing to help maintain this package
