### ISSUE TITLE
[Wolfi Package Request]: helix

### ISSUE THREAD

**Issue by storopoli** [wolfi-dev/os#11777]
### What software would you like us to add to wolfi-os. Ideally include a URL to the project and its source.

Helix is a vim-inspired Rust terminal editor.

Project homepage: https://helix-editor.com/
GitHub (23k stars): https://helix-editor.com/

### which versions of the software should we include?

23.10

### Add some justification for why this specific package and versions are important.

Since wolfi is packaging neovim, helix is a good alternative that with a single binary deals with all the issues of neovim plugins.

It has out of the box:

- LSP integration
- File browser
- Fuzzy regex string finder
- Git gutter
- treesitter

### Please check all that apply

- [X] This package has an un-restrictive license
- [X] The package/versions proposed are actively maintained upstream
- [ ] I am interested in adding this package to Wolfi OS myself
- [X] I am willing to help maintain this package

**Comment by kranurag7** [comment]
+1 for this. 
I tried it during the weekend back but was not able to have `runtime` directory included with the package. 

```yaml
package:
  name: helix
  version: 23.10
  epoch: 0
  description: "just is a handy way to save and run project-specific commands."
  copyright:
    - license: CC0

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - rust
      - wolfi-base

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/helix-editor/helix
      expected-commit: f6021dd0cdd8cf6795f024e396241cb0af2ca368
      tag: ${{package.version}}

  - name: Configure and build
    runs: |
      cargo install --path helix-term --locked
      mkdir -p ${{targets.destdir}}/usr/bin/
      mv target/release/just ${{targets.destdir}}/usr/bin/

  - uses: strip

update:
  enabled: true
  github:
    identifier: helix-editor/helix
```
