### ISSUE TITLE
Build packages with many runtimes

### ISSUE THREAD

**Issue by mesaglio** [wolfi-dev/os#12281]
Hi, everyone!

I have a cuestion, in this repo we have some "application" dependencies building with melange like [py3-flask](https://github.com/wolfi-dev/os/blob/main/py3-flask.yaml) and have as buildtime dependency `python-3`.

We have many runtimes maintained to install `python-3.12`,`python-3.11`, but this type of deps (`py3-flask`) are limited when the latest runtime provide `python-3`.

Example:

- Python 3.12 - flask work
```
b3561001fb60:/# apk add py3-flask
fetch https://packages.wolfi.dev/os/aarch64/APKINDEX.tar.gz
(1/24) Installing libbz2-1 (1.0.8-r6)
(2/24) Installing libexpat1 (2.5.0-r5)
(3/24) Installing libffi (3.4.4-r4)
(4/24) Installing gdbm (1.23-r4)
(5/24) Installing xz (5.4.6-r0)
(6/24) Installing libgcc (13.2.0-r4)
(7/24) Installing libstdc++ (13.2.0-r4)
(8/24) Installing mpdecimal (4.0.0-r0)
(9/24) Installing ncurses-terminfo-base (6.4_p20231125-r1)
(10/24) Installing ncurses (6.4_p20231125-r1)
(11/24) Installing readline (8.2-r3)
(12/24) Installing sqlite-libs (3.45.1-r0)
(13/24) Installing python-3.12 (3.12.1-r1)
(14/24) Installing py3-blinker (1.7.0-r1)
(15/24) Installing py3-colorama (0.4.6-r3)
(16/24) Installing py3-typing-extensions (4.9.0-r1)
(17/24) Installing py3-zipp (3.17.0-r2)
(18/24) Installing py3-importlib-metadata (7.0.1-r0)
(19/24) Installing py3-click (8.1.7-r2)
(20/24) Installing py3-itsdangerous (2.1.2-r1)
(21/24) Installing py3-markupsafe (2.1.4-r0)
(22/24) Installing py3-jinja2 (3.1.3-r1)
(23/24) Installing py3-werkzeug (3.0.1-r0)
(24/24) Installing py3-flask (3.0.1-r1)
OK: 61 MiB in 38 packages
b3561001fb60:/# python3 -c 'import flask'
b3561001fb60:/#
```

- Python 3.11 - flask not found
```
0672e9be0319:/# apk add python-3.11 py3-flask
fetch https://packages.wolfi.dev/os/aarch64/APKINDEX.tar.gz
(1/24) Installing libbz2-1 (1.0.8-r6)
(2/24) Installing libexpat1 (2.5.0-r5)
(3/24) Installing libffi (3.4.4-r4)
(4/24) Installing gdbm (1.23-r4)
(5/24) Installing xz (5.4.6-r0)
(6/24) Installing libgcc (13.2.0-r4)
(7/24) Installing libstdc++ (13.2.0-r4)
(8/24) Installing mpdecimal (4.0.0-r0)
(9/24) Installing ncurses-terminfo-base (6.4_p20231125-r1)
(10/24) Installing ncurses (6.4_p20231125-r1)
(11/24) Installing readline (8.2-r3)
(12/24) Installing sqlite-libs (3.45.1-r0)
(13/24) Installing python-3.11 (3.11.7-r1)
(14/24) Installing py3-blinker (1.7.0-r1)
(15/24) Installing py3-colorama (0.4.6-r3)
(16/24) Installing py3-typing-extensions (4.9.0-r1)
(17/24) Installing py3-zipp (3.17.0-r2)
(18/24) Installing py3-importlib-metadata (7.0.1-r0)
(19/24) Installing py3-click (8.1.7-r2)
(20/24) Installing py3-itsdangerous (2.1.2-r1)
(21/24) Installing py3-markupsafe (2.1.4-r0)
(22/24) Installing py3-jinja2 (3.1.2-r4)
(23/24) Installing py3-werkzeug (3.0.1-r0)
(24/24) Installing py3-flask (3.0.1-r1)
OK: 61 MiB in 38 packages
0672e9be0319:/# python3 -c 'import flask'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'flask'
0672e9be0319:/#
```
---
I've been thinking in a posible solution adding a melange capability. Some like [github matrix build strategy](https://docs.github.com/en/actions/using-jobs/using-a-matrix-for-your-jobs#using-a-matrix-strategy).
This is needed as package level, like:
```yaml
package:
  name: py3-flask
  version: 3.0.1
  epoch: 1
  description: A simple framework for building complex web applications.
  copyright:
    - license: BSD-3-Clause
  matrix:
    py_version: ["3", "3.11", "3.10"]
```
And the final package, it would be like:
```yaml
# Generated from https://pypi.org/project/Flask/
package:
  name: py3-flask
  version: 3.0.1
  epoch: 1
  description: A simple framework for building complex web applications.
  copyright:
    - license: BSD-3-Clause
  matrix:
    py_version: ["3", "3.11", "3.10"]
  dependencies:
    runtime:
      - py${{vars.py_version}}-werkzeug
      - py${{vars.py_version}}-jinja2
      - py${{vars.py_version}}-itsdangerous
      - py${{vars.py_version}}-click
      - py${{vars.py_version}}-blinker
      - py${{vars.py_version}}-importlib-metadata
      - python-${{vars.py_version}}

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - py${{vars.py_version}}-setuptools
      - python-${{vars.py_version}}
      - wolfi-base

pipeline:
  - uses: fetch
    with:
      expected-sha256: 6489f51bb3666def6f314e15f19d50a1869a19ae0e8c9a3641ffe66c77d42403
      uri: https://files.pythonhosted.org/packages/source/f/flask/flask-${{package.version}}.tar.gz

  - name: Python Build
    uses: python/build-wheel

  - uses: strip

update:
  enabled: true
  release-monitor:
    identifier: 3867
```

cc @lpcalisi
