### ISSUE TITLE
Issues Adding AZ package in my custom wolfi container

### ISSUE THREAD

**Issue by noelmiller** [wolfi-dev/os#12419]
Hey folks! 

I was having an issue adding the `az` package to my custom wolfi container. My container is: `ghcr.io/noelmiller/isengard-cli:latest`. 

Here is the error with my build: https://github.com/noelmiller/isengard-cli/actions/runs/7766253100/job/21181863932

When installing it as the only package in `ghcr.io/ublue-os-wolfi-toolbox:latest`, it works just fine.

Is there some kind of dependency conflict that is happening here?

Thanks, 

Noel

**Comment by ajayk** [comment]
`az` package brings as python3.11 as dependency and `aws-cli` brings python 3.12 as dependency which conflicts with some of the files owned by python3.11 

```
(12/16) Installing python-3.12 (3.12.0-r0)
WARNING: python-3.12-3.12.0-r0: overwriting usr/bin/2to3 owned by python-3.11-3.11.2-r0.
WARNING: python-3.12-3.12.0-r0: overwriting usr/bin/idle3 owned by python-3.11-3.11.2-r0.
WARNING: python-3.12-3.12.0-r0: overwriting usr/bin/pydoc3 owned by python-3.11-3.11.2-r0.
WARNING: python-3.12-3.12.0-r0: overwriting usr/bin/python owned by python-3.11-3.11.2-r0.
WARNING: python-3.12-3.12.0-r0: overwriting usr/bin/python3 owned by python-3.11-3.11.2-r0.
WARNING: python-3.12-3.12.0-r0: overwriting usr/lib/libpython3.so owned by python-3.11-3.11.2-r0.
```

currently two concurrent versions of python cannot co-exist at the moment on wolfi

**Comment by noelmiller** [comment]
Sounds good! Are there any plans to allow concurrent versions of python or other dependencies to exist in a single Wolfi container?

**Comment by noelmiller** [comment]
> Can this idea #12281 help in this case?

Not 100% sure. I'm assuming it might?

**Comment by jalmeroth** [comment]
Hi, I did some hacking because I had the same issue.

I basically built some empty local packages for `python3.11` and `python3.12` with melange:

```yaml
#  latest.python3.11.melange.yaml

package:
  name: python3
  version: 3.11.999
  epoch: 0
  description: "The Python programming language"
  dependencies:
    provides:
      - python3=${{package.full-version}}
      - python-3=${{package.full-version}}
  target-architecture:
    - aarch64
    - x86_64

environment:
  contents:
    packages:
      - busybox

pipeline:
  - working-directory: "${{targets.destdir}}"
    runs: |
      touch "__${{package.name}}-${{package.full-version}}_was_here__"
```

```yaml
# latest.python3.12.melange.yaml

package:
  name: python-3.12
  version: 3.12.999
  epoch: 0
  description: "The Python programming language"
  dependencies:
    provides:
      - python-3.12=${{package.full-version}}
  target-architecture:
    - aarch64
    - x86_64

environment:
  contents:
    packages:
      - busybox

pipeline:
  - working-directory: "${{targets.destdir}}"
    runs: |
      touch "__${{package.name}}-${{package.full-version}}_was_here__"
  - working-directory: "${{targets.destdir}}/usr/bin"
    runs: |
      ln -s /usr/bin/python3.12 python3
      ln -s /usr/bin/python3 python
```

Then I combined them using apko and my local packages:

```yaml
# latest.awesome-cli.apko.yaml

contents:
  keyring:
    - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
    - signing.rsa.pub # local signing key
  repositories:
    - "@local packages"
    - https://packages.wolfi.dev/os
  packages:
    - aws-cli
    - az
    - busybox
    - python-3.11-base
    - python-3.12-base
    - python-3.12@local # python-3.12-3.12.999-r0
    - python3@local # python3-3.11.999-r0

accounts:
  groups:
    - groupname: nonroot
      gid: 65532
  users:
    - username: nonroot
      uid: 65532
  run-as: 65532

archs:
  - aarch64
  - x86_64
```

As I said: it's a hack and I wouldn't recommend doing it, but it kinda works! :partying_face:

```sh
/ $ aws --version
aws-cli/1.32.70 Python/3.12.2 Linux/6.8.1-arch1-1 botocore/1.34.70
/ $ az version
{
  "azure-cli": "2.58.0",
  "azure-cli-core": "2.58.0",
  "azure-cli-telemetry": "1.1.0",
  "extensions": {}
}
/ $
/ $ ls -al /var/lib/db/sbom/
total 43916
drwxr-xr-x    2 root     root          4096 Jan  1  1970 .
drwxr-xr-x    3 root     root          4096 Jan  1  1970 ..
-rw-r--r--    1 root     root       6903206 Jan  1  1970 aws-cli-1.32.70-r0.spdx.json
-rw-r--r--    1 root     root      30343396 Jan  1  1970 az-2.58.0-r0.spdx.json
-rw-r--r--    1 root     root          3902 Jan  1  1970 busybox-1.36.1-r6.spdx.json
-rw-r--r--    1 root     root          2320 Jan  1  1970 ca-certificates-bundle-20240315-r0.spdx.json
-rw-r--r--    1 root     root         22760 Jan  1  1970 gdbm-1.23-r4.spdx.json
-rw-r--r--    1 root     root         17794 Jan  1  1970 glibc-2.38-r14.spdx.json
-rw-r--r--    1 root     root         12794 Jan  1  1970 glibc-locale-posix-2.38-r14.spdx.json
-rw-r--r--    1 root     root        518624 Jan  1  1970 groff-1.23.0-r1.spdx.json
-rw-r--r--    1 root     root          3922 Jan  1  1970 ld-linux-2.38-r14.spdx.json
-rw-r--r--    1 root     root          2189 Jan  1  1970 libbz2-1-1.0.8-r6.spdx.json
-rw-r--r--    1 root     root          2172 Jan  1  1970 libcrypt1-2.38-r14.spdx.json
-rw-r--r--    1 root     root          3134 Jan  1  1970 libcrypto3-3.2.1-r0.spdx.json
-rw-r--r--    1 root     root          2191 Jan  1  1970 libexpat1-2.6.2-r0.spdx.json
-rw-r--r--    1 root     root          2172 Jan  1  1970 libffi-3.4.6-r0.spdx.json
-rw-r--r--    1 root     root          2189 Jan  1  1970 libgcc-13.2.0-r5.spdx.json
-rw-r--r--    1 root     root          2162 Jan  1  1970 libssl3-3.2.1-r0.spdx.json
-rw-r--r--    1 root     root          3217 Jan  1  1970 libstdc++-13.2.0-r5.spdx.json
-rw-r--r--    1 root     root          6846 Jan  1  1970 mpdecimal-4.0.0-r0.spdx.json
-rw-r--r--    1 root     root         15465 Jan  1  1970 ncurses-6.4_p20231125-r1.spdx.json
-rw-r--r--    1 root     root        264407 Jan  1  1970 ncurses-terminfo-base-6.4_p20231125-r1.spdx.json
-rw-r--r--    1 root     root          6724 Jan  1  1970 openssl-config-3.2.1-r0.spdx.json
-rw-r--r--    1 root     root         85745 Jan  1  1970 py3-asn1-0.4.8-r6.spdx.json
-rw-r--r--    1 root     root       2089554 Jan  1  1970 py3-botocore-1.34.70-r0.spdx.json
-rw-r--r--    1 root     root         25612 Jan  1  1970 py3-colorama-0.4.6-r3.spdx.json
-rw-r--r--    1 root     root        379197 Jan  1  1970 py3-docutils-0.20.1-r3.spdx.json
-rw-r--r--    1 root     root         23876 Jan  1  1970 py3-jmespath-1.0.1-r4.spdx.json
-rw-r--r--    1 root     root         26733 Jan  1  1970 py3-python-dateutil-2.9.0-r0.spdx.json
-rw-r--r--    1 root     root         43299 Jan  1  1970 py3-rsa-4.9-r4.spdx.json
-rw-r--r--    1 root     root         41839 Jan  1  1970 py3-s3transfer-0.10.1-r0.spdx.json
-rw-r--r--    1 root     root          7710 Jan  1  1970 py3-six-1.16.0-r7.spdx.json
-rw-r--r--    1 root     root         85976 Jan  1  1970 py3-urllib3-2.2.1-r0.spdx.json
-rw-r--r--    1 root     root         44973 Jan  1  1970 py3-yaml-6.0.1-r2.spdx.json
-rw-r--r--    1 root     root        559810 Jan  1  1970 py3.12-setuptools-69.2.0-r0.spdx.json
-rw-r--r--    1 root     root       1644290 Jan  1  1970 python-3.11-base-3.11.8-r5.spdx.json
-rw-r--r--    1 root     root          2276 Jan  1  1970 python-3.12-3.12.999-r0.spdx.json
-rw-r--r--    1 root     root       1541802 Jan  1  1970 python-3.12-base-3.12.2-r8.spdx.json
-rw-r--r--    1 root     root          2236 Jan  1  1970 python3-3.11.999-r0.spdx.json
-rw-r--r--    1 root     root         10410 Jan  1  1970 readline-8.2-r3.spdx.json
-rw-r--r--    1 root     root          2222 Jan  1  1970 sqlite-libs-3.45.1-r0.spdx.json
-rw-r--r--    1 root     root         12591 Jan  1  1970 wolfi-baselayout-20230201-r7.spdx.json
-rw-r--r--    1 root     root        108891 Jan  1  1970 xz-5.6.1-r0.spdx.json
-rw-r--r--    1 root     root          2165 Jan  1  1970 yaml-0.2.5-r2.spdx.json
-rw-r--r--    1 root     root          3039 Jan  1  1970 zlib-1.3.1-r0.spdx.json
```
