### ISSUE TITLE
[Wolfi Package Request]: apache2-utils

### ISSUE THREAD

**Issue by Nabsku** [wolfi-dev/os#16476]
### What software would you like us to add to wolfi-os. Ideally include a URL to the project and its source.

For some image builds, a working copy of htpasswd is needed as openssl doesn't support all the functions that htpasswd provides. 

This is included in the apk apache2-utils, from the apache httpd project.

https://httpd.apache.org/

### which versions of the software should we include?

any, 2.4.59-r0

### Add some justification for why this specific package and versions are important.

For some image builds, a working copy of htpasswd is needed as openssl doesn't support all the functions that htpasswd provides. 

### Please check all that apply

- [x] This package has an un-restrictive license
- [X] The package/versions proposed are actively maintained upstream
- [X] I am interested in adding this package to Wolfi OS myself
- [X] I am willing to help maintain this package

**Comment by tuananh** [comment]
@Nabsku i opened a PR for this here https://github.com/wolfi-dev/os/pull/14887/files

**Comment by Nabsku** [comment]
> @Nabsku i opened a PR for this here https://github.com/wolfi-dev/os/pull/14887/files

Oh I didn’t check open issues. Albeit I’d wager that not everyone might want to install a full-blown apache server to utilise tools like htpasswd. I can build a smaller package later. But thanks for the input and great work! :)

**Comment by tuananh** [comment]
> > @Nabsku i opened a PR for this here https://github.com/wolfi-dev/os/pull/14887/files
> 
> Oh I didn’t check open issues. Albeit I’d wager that not everyone might want to install a full-blown apache server to utilise tools like htpasswd. I can build a smaller package later. But thanks for the input and great work! :)

there's `apache2-utils` subpackage in there

```yaml
  - name: ${{package.name}}-utils
    description: "Apache utility programs for webservers"
    pipeline:
      - runs: |
          mkdir -p "${{targets.contextdir}}"/usr/sbin
          for i in checkgid htcacheclean rotatelogs envvars envvars-std; do
            mv "${{targets.destdir}}"/usr/sbin/$i "${{targets.contextdir}}"/usr/sbin
          done
```
