### ISSUE TITLE
logstash/8.7.1 fails to build on arm in GHA

### ISSUE THREAD

**Issue by rawlingsj** [wolfi-dev/os#1778]
superseded by https://github.com/wolfi-dev/os/issues/3195

**Comment by rawlingsj** [comment]
I just created a GKE cluster and tried to recreate but the build worked successfully.  FWIW these are the steps I took
```
# create cluster + arm node
gcloud container clusters create tmp-cluster-jr \
  --enable-ip-alias \
  --zone            us-central1-b \
  --release-channel rapid \
  --machine-type    e2-standard-4 \
  --num-nodes       1 \
  --spot  \
  --no-enable-autorepair

gcloud container node-pools create arm-nodes \
  --cluster         tmp-cluster-jr \
  --zone            us-central1-b \
  --machine-type    t2a-standard-8 \
  --num-nodes       1 \
  --spot  \
  --no-enable-autorepair
```

```
# create build pod
kubectl apply -f - <<EOF
apiVersion: v1
kind: Pod
metadata:
  name: melange
spec:
  containers:
  - name: melange
    image: cgr.dev/chainguard/melange:latest
    command: ["sleep"]
    args: ["infinity"]
    securityContext:
      privileged: true
  nodeSelector:
      kubernetes.io/arch: arm64
EOF
```

```
kubectl exec -ti melange sh
apk add git

git clone https://github.com/wolfi-dev/os
cd os
melange keygen

vi logstash.yaml
# change version to 8.7.1 and expected-commit to ddd00672d403b6ea1df4e4225ad2056d19ed9404


melange build logstash.yaml  --arch aarch64 --keyring-append melange.rsa.pub --signing-key melange.rsa --keyring-append https://
packages.wolfi.dev/os/wolfi-signing.rsa.pub --repository-append https://packages.wolfi.dev/os --repository-append /work/packages
```
