### ISSUE TITLE
Traefik dashboard broken for `latest`

### ISSUE THREAD

**Issue by mocdaniel** [wolfi-dev/os#18008]
Good evening,

I just spun up the `cgr.dev/chainguard/traefik:latest` image and noticed that the dashboard seems broken (screenshot below):

<img width="844" alt="Screenshot 2024-04-29 at 20 07 04" src="https://github.com/wolfi-dev/os/assets/28064429/effd5a9e-b1f9-4ce2-b843-9d55025d1239">

The configuration of the container is fairly standard, as far as I can tell:

```yaml
services:
  traefik:
    container_name: traefik
    image: cgr.dev/chainguard/traefik:latest
    labels:
      traefik.enable: true
      traefik.http.routers.api.entrypoints: websecure
      traefik.http.routers.api.rule: Host(`traefik.bodkys.house`)
      traefik.http.routers.api.tls: true
      traefik.http.routers.api.service: api@internal
    ports:
      - 443:443
    group_add:
      - 996
    command: >
      --api.dashboard
      --providers.docker
      --providers.docker.exposedByDefault=false
      --entrypoints.websecure.address=:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped
    networks:
      - traefik

networks:
  traefik:
    external: true
```

The link from the broken dashboard [leads here](https://github.com/traefik/traefik/blob/master/webui/readme.md#how-to-build-only-for-frontend-developer), so my best guess is the frontend just wasn't built the way it's supposed to be built.

Apart from the web UI, the image works just fine. If you need a more minimal example to reproduce, let me know.
