### ISSUE TITLE
gnupg package not installed despite listing package

### ISSUE THREAD

**Issue by mark-thm** [wolfi-dev/os#19494]
Running a minimal apko file:

```
archs:
  - arm64
  - x86_64

contents:
  keyring:
    - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
  repositories:
    - https://packages.wolfi.dev/os
  packages:
    - busybox
    - gnupg
    - wolfi-base
```

Results in an image that does not actually contain `/usr/bin/gpg` or any other traces of the gnupg package.
