### ISSUE TITLE
[Wolfi Package Request]: smartmontools

### ISSUE THREAD

**Issue by sfc-gh-mhazy** [wolfi-dev/os#30024]
### What software would you like us to add to wolfi-os. Ideally include a URL to the project and its source.

Hi, would you be interested in adding smartmontools package to the distribution?

Github repo: https://github.com/smartmontools/smartmontools
main page: https://www.smartmontools.org/

### which versions of the software should we include?

7.4

### Add some justification for why this specific package and versions are important.

Both smarctl and smartd may be useful for monitoring of the containers. 

I've made a melange config and put the produced package in apko image, seems to be working:
```

package:
  name: smartmontools
  version: 7.4
  epoch: 1
  description: Smartmontools
  target-architecture:
    - aarch64
    - x86_64

environment:
  contents:
    repositories:
      - https://packages.wolfi.dev/os
    keyring:
      - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
    packages:
      - automake=1.16.5-r2
      - make 
      - jq
      - curl 
      - subversion
      - pkgconf
      - groff
      - build-base
      - libxml2-dev
      - openssl-dev
      - libbz2-1
      - unzip
      - wget
      - xorriso
      - cmake
      - git 
      - xz
      - bash
      - busybox
      - autoconf


pipeline:
  - uses: fetch
    with:
      uri: https://github.com/smartmontools/smartmontools/releases/download/RELEASE_7_4/smartmontools-7.4.tar.gz
      expected-sha256: e9a61f641ff96ca95319edfb17948cd297d0cd3342736b2c49c99d4716fb993d # pragma: allowlist secret
  - runs: ./autogen.sh
  - runs: ./configure --prefix="${{targets.destdir}}"
  - runs: make
  - runs: make install
```

The list of required packages is mainly based on https://github.com/smartmontools/docker-build/blob/master/Dockerfile

### Please check all that apply

- [X] This package has an un-restrictive license
- [X] The package/versions proposed are actively maintained upstream
- [ ] I am interested in adding this package to Wolfi OS myself
- [ ] I am willing to help maintain this package
