### ISSUE TITLE
[Wolfi Package Request]: drawio

### ISSUE THREAD

**Issue by karlhaworth** [wolfi-dev/os#31977]
### What software would you like us to add to wolfi-os. Ideally include a URL to the project and its source.

[drawio](https://github.com/jgraph/drawio-desktop) to be used in [mkdocs-drawio-exporter](https://github.com/LukeCarrier/mkdocs-drawio-exporter)

### which versions of the software should we include?

most recent

### Add some justification for why this specific package and versions are important.

I want a [drawio](https://github.com/jgraph/drawio-desktop) executable so that I can set the `drawio_executable` option in [mkdocs-drawio-exporter](https://github.com/LukeCarrier/mkdocs-drawio-exporter) allowing me to use my internal developer portal of backstage with Chainguard Images and drawio exporters so that I can have multi-page diagrams displayed in my technical documentation.

### Please check all that apply

- [ ] This package has an un-restrictive license
- [X] The package/versions proposed are actively maintained upstream
- [ ] I am interested in adding this package to Wolfi OS myself
- [X] I am willing to help maintain this package

**Comment by karlhaworth** [comment]
I had tried this here -> https://github.com/wolfi-dev/os/compare/main...AmericanAirlines:wolfi-dev-os:drawio-24.7.17--new-package but I'm not sure I made good progress. 

I also forked the repo and made some mods that I thought may be needed.

```
pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/karlhaworth/drawio-desktop
      # tag: ${{package.version}}-r${{package.epoch}}
      # expected-commit: 4e857e8bb3a0afecb1bca529579e8f239cf9c470
```
