### ISSUE TITLE
[Wolfi Package Request]: pandoc

### ISSUE THREAD

**Issue by liath** [wolfi-dev/os#40296]
### What software would you like us to add to wolfi-os. Ideally include a URL to the project and its source.

pandoc cli
https://pandoc.org
https://github.com/jgm/pandoc/

### which versions of the software should we include?

latest

### Add some justification for why this specific package and versions are important.

I use this tool for some document conversions. Sorting this out would seemingly also solve this comment from the pgbouncer config: https://github.com/wolfi-dev/os/blob/main/pgbouncer.yaml#L31

Not sure how far down the rabbit hole we'd want to go with regards to the compiler. If we can install from the official releases this should be pretty easy and I think the following ought to work:

```yaml
---
package:
  name: pandoc
  version: 3.6.2
  epoch: 0
  description: Universal markup converter
  copyright:
    - license: GPL-2.0-only
  target-architecture:
    - aarch64
    - x86_64
  dependencies:
    runtime:

environment:
  contents:
    packages:
      - busybox

pipeline:
  - uses: fetch
    with:
      uri: https://github.com/jgm/pandoc/releases/download/${{package.version}}/pandoc-${{package.version}}-linux-${{build.goarch}}.tar.gz
      expected-sha256: xxx  # unsure how to specify a SHA sum per architecture. 

update:
  enabled: true
  github:
    identifier: jgm/pandoc
    strip-prefix: "pandoc "
```

If we want to futz with compiling pandoc, we'll probably need to also make packages for the haskell toolchain (ghc, cabal, stack).

### Please check all that apply

- [x] This package has an un-restrictive license
- [x] The package/versions proposed are actively maintained upstream
- [x] I am interested in adding this package to Wolfi OS myself
- [x] I am willing to help maintain this package
