### ISSUE TITLE
wolfi image shows critical glibc vulnerability

### ISSUE THREAD

**Issue by kapilt** [wolfi-dev/os#4125]
doing a fresh build with apko

```yaml
contents:
  packages:
    - build-base
    - python-3.11
    - git
  keyring:
    - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
  repositories:
    - https://packages.wolfi.dev/os

entrypoint:
  command: /usr/bin/python

accounts:
  groups:
    - groupname: nonroot
      gid: 65532
  users:
    - username: nonroot
      uid: 65532
      gid: 65532
  run-as: 65532
```

and then running a scan shows a critical glibc vulnerability.

![Screenshot 2023-08-01 at 6 34 42 PM](https://github.com/wolfi-dev/os/assets/21650/75eaee8a-3c6e-4827-ae28-afcb903107b0)

comparing to the chain guard python image, though which shows zero.

![Screenshot 2023-08-01 at 6 33 21 PM](https://github.com/wolfi-dev/os/assets/21650/d2af7440-c79c-4e5c-9279-e803848eb9d9)

am I missing something, cause it doesn't really add up.
