### ISSUE TITLE
[Wolfi Package Request]: conftest

### ISSUE THREAD

**Issue by adam-moss** [wolfi-dev/os#4513]
### What software would you like us to add to wolfi-os. Ideally include a URL to the project and its source.

Open Policy Agent's `conftest`

https://conftest.dev
https://github.com/open-policy-agent/conftest

### which versions of the software should we include?

latest

### Add some justification for why this specific package and versions are important.

`conftest` is used to validate structured configuration files through `rego` policies.

### Please check all that apply

- [X] This package has an un-restrictive license
- [X] The package/versions proposed are actively maintained upstream
- [X] I am interested in adding this package to Wolfi OS myself
- [X] I am willing to help maintain this package

**Comment by developer-guy** [comment]
Hello @adam-moss, thanks for raising an issue! I just noticed you tended to package it by yourself, so, please do not hesitate to ping me if you need anything, cheers!

**Comment by adam-moss** [comment]
Yes, I'll give it a go 😄

**Comment by adam-moss** [comment]
Hey @developer-guy, question if I may?  My dev environment is stuck behind an intercepting proxy doing TLS inspection, so I get a barrage of:

```console
Get "https://proxy.golang.org/cuelang.org/go/@v/v0.4.0.zip": tls: failed to verify certificate: x509: certificate signed by unknown authority
```

How can I inject the proxy cert into melange?

I'm using the `go/build` pipeline.

Cheers

**Comment by goproslowyo** [comment]
@adam-moss you'll want to get your intercepting proxy's root CA certs (and any intermediary) and add them to this certificate bundle: `/etc/ssl/certs/ca-certificates.crt`.

Something along the lines of:
```docker
FROM cgr.dev/chainguard/wolfi-base
COPY yourInternalCACert.pem /usr/local/share/ca-certificates/my-cert.crt
RUN cat /usr/local/share/ca-certificates/my-cert.crt >> /etc/ssl/certs/ca-certificates.crt
```

**Comment by adam-moss** [comment]
Thanks @goproslowyo I'd already tried that without success.  Works fine for executing but not for building.  It seems part of the melange process is creating a bubblewrap container and the cert chain isn't included from the melange image

```console
image configuration:
ℹ️  x86_64    |   contents:
ℹ️  x86_64    |     repositories: [https://packages.wolfi.dev/os]
ℹ️  x86_64    |     keyring:      [https://packages.wolfi.dev/os/wolfi-signing.rsa.pub]
ℹ️  x86_64    |     packages:     [busybox ca-certificates-bundle git go]
...
executing: bwrap --bind /tmp/melange-guest-3943782 ...
```

So it looks like I need to include it in that somehow.

**Comment by goproslowyo** [comment]
Ah, yea understood. Bubblewrap is used to perform the build in an isolated environment -- I'll have to play around to see if I can figure that out. Alternatively, I can look into packaging this up :)

**Comment by adam-moss** [comment]
Having scoured the docs I *think* what I need to do is build an apko package with the cert to include as part of the `environment` directive. Just gotta work out how to append rather than replace the ca-certs package

**Comment by adam-moss** [comment]
Ok, got a little bit closer, now `apko` is giving me grief 🤣 

```yaml
package:
  name: my-internal-certificate
  version: 1.0.0
  epoch: 0
  description: "my internal certificate"
  target-architecture:
    - x86_64

environment:
  contents:
    keyring:
      - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
      - melange.rsa.pub

    repositories:
      - https://packages.wolfi.dev/os

    packages:
      - busybox
      - ca-certificates-bundle

pipeline:
  - runs: >
      mkdir -p "${{targets.destdir}}"/etc/ssl/certs

      cp /etc/ssl/certs/ca-certificates.crt "${{targets.destdir}}"/etc/ssl/certs

      printf -- '-----BEGIN CERTIFICATE-----\n
      ...
      -----END CERTIFICATE-----' > "${{targets.destdir}}"/etc/ssl/certs/ca-certificates.crt
```

Builds an apk successfully, but when install with `apko` I get

```console
 installing apk packages: installing packages: installing my-internal-certificate: unable to install files for pkg my-internal-certificate: unable to install file over existing one, different contents: etc/ssl/certs/ca-certificates.crt
```
