### ISSUE TITLE
pnpm is missing a runtime dependency

### ISSUE THREAD

**Issue by murraybd** [wolfi-dev/os#47343]
It seems to me like `pnpm` is missing a runtime dependency on nodejs:

```
4002e2885c68:/work/packages# apk add pnpm
(1/1) Installing pnpm (10.6.1-r0)
Executing busybox-1.37.0-r30.trigger
OK: 37 MiB in 17 packages
4002e2885c68:/work/packages# pnpm config set package-import-method copy
env: can't execute 'node': No such file or directory
4002e2885c68:/work/packages# apk add nodejs
(1/9) Installing libbrotlicommon1 (1.1.0-r4)
(2/9) Installing libbrotlidec1 (1.1.0-r4)
(3/9) Installing libbrotlienc1 (1.1.0-r4)
(4/9) Installing c-ares (1.34.4-r2)
(5/9) Installing libstdc++ (14.2.0-r11)
(6/9) Installing icu (75.1-r0)
(7/9) Installing libnghttp2-14 (1.65.0-r0)
(8/9) Installing libuv (1.50.0-r1)
(9/9) Installing nodejs-23 (23.10.0-r1)
Executing busybox-1.37.0-r30.trigger
OK: 158 MiB in 26 packages
4002e2885c68:/work/packages# pnpm config set package-import-method copy
```

Looking at pnpm.yaml a version of nodejs is added as a test dependency and I think it really should be a runtime dep.

```
test:
  environment:
    contents:
      packages:
        - nodejs-18
  pipeline:
    - runs: |
        set -o pipefail
        pnpm --version | grep "${{package.version}}"
```
