### ISSUE TITLE
Clean up use of contextdir, destdir, and subpkgdir

### ISSUE THREAD

**Issue by vaikas** [wolfi-dev/os#7347]
subpkgdir / destdir cause some mistakes,  because using destdir within subpkg is incorrect. Preference should be to use `contextdir` which is safe/correct from the subpackage. So we should look at changing all the existing uses of it and deprecate it.

There was an attempt to do this in a cheap & cheerful way, but it surfaced some further issues.

```yaml
subpackages:
  - name: "scanelf"
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}"/usr/bin
          mv "${{targets.destdir}}"/usr/bin/scanelf "${{targets.subpkgdir}}"/usr/bin/scanelf
```

This pulls a file out of the main package filesystem and puts it in the subpackage filesystem, and changing both of those to `${{targets.contextdir}}` doesn't work.

So at the very least we need to do something smarter than this, and at most it might not be possible to do what we want to do. Closing this for now, but it's still something we should investigate.

We might want to change all `subpkgdir`s to `contextdirs` -- that should be safe

We might also want to do a deeper analysis of `destdir` references in subpackages, to ensure things aren't writing to the wrong place. We could make melange smarter here about detecting files written to `destdir` from a subpackage pipeline, and fail loudly and clearly.

_Originally posted by @imjasonh in https://github.com/wolfi-dev/os/issues/7337#issuecomment-1777984903_
