### ISSUE TITLE
new zlib-cloudflare package breaks ruby3.2-bundler (possibly others)

### ISSUE THREAD

**Issue by joemiller** [wolfi-dev/os#9370]
The recently added `zlib-cloudflare` package appears to break the `ruby3.2-bundler` package and possibly others.

Quickest way to repro is build a ruby image with bundler and run `bundle`:

Example:

```yaml
contents:
  keyring:
    - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
  repositories:
    - https://packages.wolfi.dev/os
  packages:
    - ca-certificates-bundle
    - wolfi-base
    - wolfi-baselayout
    - tzdata
    - ruby-3.2
    - ruby3.2-bundler

accounts:
  groups:
    - groupname: nonroot
      gid: 65532
  users:
    - username: nonroot
      uid: 65532
      gid: 65532
  run-as: 65532

paths:
  - path: /work
    type: directory
    permissions: 0o777

work-dir: /work

entrypoint:
  command: /usr/bin/ruby
cmd: --version

archs:
  - x86_64
  - aarch64
```

```console
$ apko publish --local --arch host ruby-apko.yaml my-ruby:3.2

...
apko.local/cache:940b84c958936cb9eafd9759dbb5564e52b4f15852b800430578a8e37d9239eb
```

```console
$ docker run --rm -it --entrypoint sh apko.local/cache:940b84c958936cb9eafd9759dbb5564e52b4f15852b800430578a8e37d9239eb

/work $ bundle
--- ERROR REPORT TEMPLATE -------------------------------------------------------

LoadError: /usr/lib/ruby/3.2.0/x86_64-linux-gnu/zlib.so: undefined symbol: crc32_z, version ZLIB_1.2.9 - /usr/lib/ruby/3.2.0/x86_64-linux-gnu/zlib.so
  <internal:/usr/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
  <internal:/usr/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
  /usr/lib/ruby/gems/3.2.0/gems/bundler-2.4.22/lib/bundler/fetcher.rb:6:in `<top (required)>'
  <internal:/usr/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
  <internal:/usr/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
  /usr/lib/ruby/gems/3.2.0/gems/bundler-2.4.22/lib/bundler/cli/install.rb:50:in `run'
  /usr/lib/ruby/gems/3.2.0/gems/bundler-2.4.22/lib/bundler/cli.rb:261:in `block in install'
  /usr/lib/ruby/gems/3.2.0/gems/bundler-2.4.22/lib/bundler/settings.rb:142:in `temporary'
  /usr/lib/ruby/gems/3.2.0/gems/bundler-2.4.22/lib/bundler/cli.rb:260:in `install'
  /usr/lib/ruby/gems/3.2.0/gems/bundler-2.4.22/lib/bundler/vendor/thor/lib/thor/command.rb:28:in `run'
  /usr/lib/ruby/gems/3.2.0/gems/bundler-2.4.22/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
  /usr/lib/ruby/gems/3.2.0/gems/bundler-2.4.22/lib/bundler/vendor/thor/lib/thor.rb:527:in `dispatch'
  /usr/lib/ruby/gems/3.2.0/gems/bundler-2.4.22/lib/bundler/cli.rb:34:in `dispatch'
  /usr/lib/ruby/gems/3.2.0/gems/bundler-2.4.22/lib/bundler/vendor/thor/lib/thor/base.rb:584:in `start'
  /usr/lib/ruby/gems/3.2.0/gems/bundler-2.4.22/lib/bundler/cli.rb:28:in `start'
  /usr/lib/ruby/gems/3.2.0/gems/bundler-2.4.22/exe/bundle:37:in `block in <top (required)>'
  /usr/lib/ruby/gems/3.2.0/gems/bundler-2.4.22/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
  /usr/lib/ruby/gems/3.2.0/gems/bundler-2.4.22/exe/bundle:29:in `<top (required)>'
  /usr/bin/bundle:25:in `load'
  /usr/bin/bundle:25:in `<main>'

## Environment

Bundler       2.4.22
  Platforms   ruby, x86_64-linux-gnu
Ruby          3.2.2p53 (2023-03-30 revision e51014f9c05aa65cbf203442d37fef7c12390015) [x86_64-linux-gnu]
  Full Path   /usr/bin/ruby
  Config Dir  /usr/etc
RubyGems      3.4.10
  Gem Home    /usr/lib/ruby/gems/3.2.0
  Gem Path    /home/nonroot/.local/share/gem/ruby/3.2.0:/usr/lib/ruby/gems/3.2.0
  User Home   /home/nonroot
  User Path   /home/nonroot/.local/share/gem/ruby/3.2.0
  Bin Dir     /usr/bin
OpenSSL       
  Compiled    OpenSSL 3.1.2 1 Aug 2023
  Loaded      OpenSSL 3.2.0 23 Nov 2023
  Cert File   /etc/ssl/cert.pem
  Cert Dir    /etc/ssl/certs
Tools         
  Git         not installed
  RVM         not installed
  rbenv       not installed
  chruby      not installed

## Bundler Build Metadata

Built At          2023-12-04
Git SHA           unknown
Released Version  false

--- TEMPLATE END ----------------------------------------------------------------

Unfortunately, an unexpected error occurred, and Bundler cannot continue.

First, try this link to see if there are any existing issue reports for this error:
https://github.com/rubygems/rubygems/search?q=%2Fusr%2Flib%2Fruby%2F3.2.0%2Fx86_64-linux-gnu%2Fzlib.so++undefined+symbol++crc32_z%2C+version+ZLIB_1.2.9+-+%2Fusr%2Flib%2Fruby%2F3.2.0%2Fx86_64-linux-gnu%2Fzlib.so&type=Issues

If there aren't any reports for this error yet, please fill in the new issue form located at https://github.com/rubygems/rubygems/issues/new?labels=Bundler&template=bundler-related-issue.md, and copy and paste the report template above in there.
```

Workaround: temporarily pin to zlib-1.3 r2 packages in the apko yaml `contents.packages` section:
```yaml
    - zlib=1.3-r2
    - zlib-dev=1.3-42
```
